linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - forbidigo
    - lll
    - gofmt

linters-settings:
  forbidigo:
    forbid:
      - os.Exit
      - log.Fatal.*

  lll:
    line-length: 150

issues:
  exclude-rules:
    - path: main.go
      linters:
        - forbidigo
