version: "2"
linters:
  default: none
  enable:
    - errcheck
    - forbidigo
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    forbidigo:
      forbid:
        - pattern: os.Exit
        - pattern: log.Fatal.*
    lll:
      line-length: 150
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
